/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.linkedin.events.sas;
/*
 *
 * Copyright 2013 LinkedIn Corp. All rights reserved
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 *
*/


@SuppressWarnings("all")
/** Auto-generated Avro schema for sas.sy$performance_1. Generated at Sep 15, 2011 02:52:34 PM PDT */
public class Performance_V1 extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = org.apache.avro.Schema.parse("{\"type\":\"record\",\"name\":\"Performance_V1\",\"namespace\":\"com.linkedin.events.sas\",\"fields\":[{\"name\":\"txn\",\"type\":[\"int\",\"null\"],\"meta\":\"dbFieldName=TXN;dbFieldPosition=0;\"},{\"name\":\"key\",\"type\":[\"int\",\"null\"],\"meta\":\"dbFieldName=KEY;dbFieldPosition=1;\"},{\"name\":\"campaignId\",\"type\":[\"int\",\"null\"],\"meta\":\"dbFieldName=CAMPAIGN_ID;dbFieldPosition=2;\"},{\"name\":\"ctr\",\"type\":[\"long\",\"null\"],\"meta\":\"dbFieldName=CTR;dbFieldPosition=3;\"},{\"name\":\"urgency\",\"type\":[\"long\",\"null\"],\"meta\":\"dbFieldName=URGENCY;dbFieldPosition=4;\"},{\"name\":\"viewingMemberIds\",\"type\":[\"string\",\"null\"],\"meta\":\"dbFieldName=VIEWING_MEMBER_IDS;dbFieldPosition=5;\"},{\"name\":\"impressionsPerDay\",\"type\":[\"int\",\"null\"],\"meta\":\"dbFieldName=IMPRESSIONS_PER_DAY;dbFieldPosition=6;\"}],\"meta\":\"dbFieldName=sas.sy$performance_1;\"}");
  public java.lang.Integer txn;
  public java.lang.Integer key;
  public java.lang.Integer campaignId;
  public java.lang.Long ctr;
  public java.lang.Long urgency;
  public java.lang.CharSequence viewingMemberIds;
  public java.lang.Integer impressionsPerDay;
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return txn;
    case 1: return key;
    case 2: return campaignId;
    case 3: return ctr;
    case 4: return urgency;
    case 5: return viewingMemberIds;
    case 6: return impressionsPerDay;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: txn = (java.lang.Integer)value$; break;
    case 1: key = (java.lang.Integer)value$; break;
    case 2: campaignId = (java.lang.Integer)value$; break;
    case 3: ctr = (java.lang.Long)value$; break;
    case 4: urgency = (java.lang.Long)value$; break;
    case 5: viewingMemberIds = (java.lang.CharSequence)value$; break;
    case 6: impressionsPerDay = (java.lang.Integer)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
}
