/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.linkedin.events.jobs;

@SuppressWarnings("all")
public class databusCompanyT extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = org.apache.avro.Schema.parse("{\"type\":\"record\",\"name\":\"databusCompanyT\",\"namespace\":\"com.linkedin.events.jobs\",\"fields\":[{\"name\":\"companyId\",\"type\":[\"long\",\"null\"],\"meta\":\"dbFieldName=COMPANY_ID;dbFieldPosition=0;\"},{\"name\":\"companyName\",\"type\":[\"string\",\"null\"],\"meta\":\"dbFieldName=COMPANY_NAME;dbFieldPosition=1;\"}],\"meta\":\"dbFieldName=CANDIDATE_COMPANIES;dbFieldPosition=42;\"}");
  public java.lang.Long companyId;
  public java.lang.CharSequence companyName;
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return companyId;
    case 1: return companyName;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: companyId = (java.lang.Long)value$; break;
    case 1: companyName = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
}
