/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.linkedin.events.sas;

@SuppressWarnings("all")
/** Auto-generated Avro schema for sas.sy$serving_stats. Generated at Sep 15, 2011 02:53:02 PM PDT */
public class ServingStats_V1 extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = org.apache.avro.Schema.parse("{\"type\":\"record\",\"name\":\"ServingStats_V1\",\"namespace\":\"com.linkedin.events.sas\",\"fields\":[{\"name\":\"txn\",\"type\":[\"int\",\"null\"],\"meta\":\"dbFieldName=TXN;dbFieldPosition=0;\"},{\"name\":\"key\",\"type\":[\"string\",\"null\"],\"meta\":\"dbFieldName=KEY;dbFieldPosition=1;\"},{\"name\":\"campaignId\",\"type\":[\"int\",\"null\"],\"meta\":\"dbFieldName=CAMPAIGN_ID;dbFieldPosition=2;\"},{\"name\":\"creativeId\",\"type\":[\"int\",\"null\"],\"meta\":\"dbFieldName=CREATIVE_ID;dbFieldPosition=3;\"},{\"name\":\"impressionsPerDay\",\"type\":[\"int\",\"null\"],\"meta\":\"dbFieldName=IMPRESSIONS_PER_DAY;dbFieldPosition=4;\"},{\"name\":\"ctr\",\"type\":[\"int\",\"null\"],\"meta\":\"dbFieldName=CTR;dbFieldPosition=5;\"},{\"name\":\"urgency\",\"type\":[\"int\",\"null\"],\"meta\":\"dbFieldName=URGENCY;dbFieldPosition=6;\"},{\"name\":\"viewingMemberIds\",\"type\":[\"string\",\"null\"],\"meta\":\"dbFieldName=VIEWING_MEMBER_IDS;dbFieldPosition=7;\"},{\"name\":\"attributes\",\"type\":[\"int\",\"null\"],\"meta\":\"dbFieldName=ATTRIBUTES;dbFieldPosition=8;\"}],\"meta\":\"dbFieldName=sas.sy$serving_stats;\"}");
  public java.lang.Integer txn;
  public java.lang.CharSequence key;
  public java.lang.Integer campaignId;
  public java.lang.Integer creativeId;
  public java.lang.Integer impressionsPerDay;
  public java.lang.Integer ctr;
  public java.lang.Integer urgency;
  public java.lang.CharSequence viewingMemberIds;
  public java.lang.Integer attributes;
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return txn;
    case 1: return key;
    case 2: return campaignId;
    case 3: return creativeId;
    case 4: return impressionsPerDay;
    case 5: return ctr;
    case 6: return urgency;
    case 7: return viewingMemberIds;
    case 8: return attributes;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: txn = (java.lang.Integer)value$; break;
    case 1: key = (java.lang.CharSequence)value$; break;
    case 2: campaignId = (java.lang.Integer)value$; break;
    case 3: creativeId = (java.lang.Integer)value$; break;
    case 4: impressionsPerDay = (java.lang.Integer)value$; break;
    case 5: ctr = (java.lang.Integer)value$; break;
    case 6: urgency = (java.lang.Integer)value$; break;
    case 7: viewingMemberIds = (java.lang.CharSequence)value$; break;
    case 8: attributes = (java.lang.Integer)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
}
