/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.linkedin.events.targeting;
/*
 *
 * Copyright 2013 LinkedIn Corp. All rights reserved
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 *
*/


@SuppressWarnings("all")
/** Auto-generated Avro schema for sy$lix_test_3. Generated at Jul 02, 2012 07:12:55 PM PDT */
public class LixTest_V3 extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = org.apache.avro.Schema.parse("{\"type\":\"record\",\"name\":\"LixTest_V3\",\"namespace\":\"com.linkedin.events.targeting\",\"fields\":[{\"name\":\"txn\",\"type\":[\"long\",\"null\"],\"meta\":\"dbFieldName=TXN;dbFieldPosition=0;\"},{\"name\":\"key\",\"type\":[\"long\",\"null\"],\"meta\":\"dbFieldName=KEY;dbFieldPosition=1;\"},{\"name\":\"id\",\"type\":[\"long\",\"null\"],\"meta\":\"dbFieldName=ID;dbFieldPosition=2;\"},{\"name\":\"testkey\",\"type\":[\"string\",\"null\"],\"meta\":\"dbFieldName=TESTKEY;dbFieldPosition=3;\"},{\"name\":\"defaultTreatment\",\"type\":[\"string\",\"null\"],\"meta\":\"dbFieldName=DEFAULT_TREATMENT;dbFieldPosition=4;\"},{\"name\":\"state\",\"type\":[\"string\",\"null\"],\"meta\":\"dbFieldName=STATE;dbFieldPosition=5;\"},{\"name\":\"created\",\"type\":[\"long\",\"null\"],\"meta\":\"dbFieldName=CREATED;dbFieldPosition=6;\"},{\"name\":\"experimentid\",\"type\":[\"long\",\"null\"],\"meta\":\"dbFieldName=EXPERIMENTID;dbFieldPosition=7;\"},{\"name\":\"runid\",\"type\":[\"long\",\"null\"],\"meta\":\"dbFieldName=RUNID;dbFieldPosition=8;\"},{\"name\":\"experimentstate\",\"type\":[\"string\",\"null\"],\"meta\":\"dbFieldName=EXPERIMENTSTATE;dbFieldPosition=9;\"},{\"name\":\"isonline\",\"type\":[\"string\",\"null\"],\"meta\":\"dbFieldName=ISONLINE;dbFieldPosition=10;\"},{\"name\":\"experimentdsl\",\"type\":[\"string\",\"null\"],\"meta\":\"dbFieldName=EXPERIMENTDSL;dbFieldPosition=11;\"},{\"name\":\"enabletracking\",\"type\":[\"string\",\"null\"],\"meta\":\"dbFieldName=ENABLETRACKING;dbFieldPosition=12;\"}],\"meta\":\"dbFieldName=sy$lix_test_3;pk=key;\"}");
  public java.lang.Long txn;
  public java.lang.Long key;
  public java.lang.Long id;
  public java.lang.CharSequence testkey;
  public java.lang.CharSequence defaultTreatment;
  public java.lang.CharSequence state;
  public java.lang.Long created;
  public java.lang.Long experimentid;
  public java.lang.Long runid;
  public java.lang.CharSequence experimentstate;
  public java.lang.CharSequence isonline;
  public java.lang.CharSequence experimentdsl;
  public java.lang.CharSequence enabletracking;
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return txn;
    case 1: return key;
    case 2: return id;
    case 3: return testkey;
    case 4: return defaultTreatment;
    case 5: return state;
    case 6: return created;
    case 7: return experimentid;
    case 8: return runid;
    case 9: return experimentstate;
    case 10: return isonline;
    case 11: return experimentdsl;
    case 12: return enabletracking;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: txn = (java.lang.Long)value$; break;
    case 1: key = (java.lang.Long)value$; break;
    case 2: id = (java.lang.Long)value$; break;
    case 3: testkey = (java.lang.CharSequence)value$; break;
    case 4: defaultTreatment = (java.lang.CharSequence)value$; break;
    case 5: state = (java.lang.CharSequence)value$; break;
    case 6: created = (java.lang.Long)value$; break;
    case 7: experimentid = (java.lang.Long)value$; break;
    case 8: runid = (java.lang.Long)value$; break;
    case 9: experimentstate = (java.lang.CharSequence)value$; break;
    case 10: isonline = (java.lang.CharSequence)value$; break;
    case 11: experimentdsl = (java.lang.CharSequence)value$; break;
    case 12: enabletracking = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
}
