/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.linkedin.events.anet;

@SuppressWarnings("all")
public class SETTINGS_T extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = org.apache.avro.Schema.parse("{\"type\":\"record\",\"name\":\"SETTINGS_T\",\"namespace\":\"com.linkedin.events.anet\",\"fields\":[{\"name\":\"settings\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"settingT\",\"fields\":[{\"name\":\"entityId\",\"type\":[\"long\",\"null\"],\"meta\":\"dbFieldName=ENTITY_ID;dbFieldPosition=0;\"},{\"name\":\"settingId\",\"type\":[\"long\",\"null\"],\"meta\":\"dbFieldName=SETTING_ID;dbFieldPosition=1;\"},{\"name\":\"settingValue\",\"type\":[\"string\",\"null\"],\"meta\":\"dbFieldName=SETTING_VALUE;dbFieldPosition=2;\"},{\"name\":\"dateCreated\",\"type\":[\"long\",\"null\"],\"meta\":\"dbFieldName=DATE_CREATED;dbFieldPosition=3;\"},{\"name\":\"dateModified\",\"type\":[\"long\",\"null\"],\"meta\":\"dbFieldName=DATE_MODIFIED;dbFieldPosition=4;\"}],\"meta\":\"dbFieldName=SETTINGS;dbFieldPosition=0;\"}}}]}");
  public java.util.List<com.linkedin.events.anet.settingT> settings;
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return settings;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: settings = (java.util.List<com.linkedin.events.anet.settingT>)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
}
