/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.linkedin.events.anet;

@SuppressWarnings("all")
public class settingT extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = org.apache.avro.Schema.parse("{\"type\":\"record\",\"name\":\"settingT\",\"namespace\":\"com.linkedin.events.anet\",\"fields\":[{\"name\":\"entityId\",\"type\":[\"long\",\"null\"],\"meta\":\"dbFieldName=ENTITY_ID;dbFieldPosition=0;\"},{\"name\":\"settingId\",\"type\":[\"long\",\"null\"],\"meta\":\"dbFieldName=SETTING_ID;dbFieldPosition=1;\"},{\"name\":\"settingValue\",\"type\":[\"string\",\"null\"],\"meta\":\"dbFieldName=SETTING_VALUE;dbFieldPosition=2;\"},{\"name\":\"dateCreated\",\"type\":[\"long\",\"null\"],\"meta\":\"dbFieldName=DATE_CREATED;dbFieldPosition=3;\"},{\"name\":\"dateModified\",\"type\":[\"long\",\"null\"],\"meta\":\"dbFieldName=DATE_MODIFIED;dbFieldPosition=4;\"}],\"meta\":\"dbFieldName=SETTINGS;dbFieldPosition=0;\"}");
  public java.lang.Long entityId;
  public java.lang.Long settingId;
  public java.lang.CharSequence settingValue;
  public java.lang.Long dateCreated;
  public java.lang.Long dateModified;
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return entityId;
    case 1: return settingId;
    case 2: return settingValue;
    case 3: return dateCreated;
    case 4: return dateModified;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: entityId = (java.lang.Long)value$; break;
    case 1: settingId = (java.lang.Long)value$; break;
    case 2: settingValue = (java.lang.CharSequence)value$; break;
    case 3: dateCreated = (java.lang.Long)value$; break;
    case 4: dateModified = (java.lang.Long)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
}
