/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.linkedin.events.company;

@SuppressWarnings("all")
public class databusCompanyLocT extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = org.apache.avro.Schema.parse("{\"type\":\"record\",\"name\":\"databusCompanyLocT\",\"namespace\":\"com.linkedin.events.company\",\"fields\":[{\"name\":\"companyLocationId\",\"type\":[\"long\",\"null\"],\"meta\":\"dbFieldName=COMPANY_LOCATION_ID;dbFieldPosition=0;\"},{\"name\":\"companyId\",\"type\":[\"long\",\"null\"],\"meta\":\"dbFieldName=COMPANY_ID;dbFieldPosition=1;\"},{\"name\":\"street1\",\"type\":[\"string\",\"null\"],\"meta\":\"dbFieldName=STREET1;dbFieldPosition=2;\"},{\"name\":\"street2\",\"type\":[\"string\",\"null\"],\"meta\":\"dbFieldName=STREET2;dbFieldPosition=3;\"},{\"name\":\"city\",\"type\":[\"string\",\"null\"],\"meta\":\"dbFieldName=CITY;dbFieldPosition=4;\"},{\"name\":\"state\",\"type\":[\"string\",\"null\"],\"meta\":\"dbFieldName=STATE;dbFieldPosition=5;\"},{\"name\":\"postalCode\",\"type\":[\"string\",\"null\"],\"meta\":\"dbFieldName=POSTAL_CODE;dbFieldPosition=6;\"},{\"name\":\"countryCode\",\"type\":[\"string\",\"null\"],\"meta\":\"dbFieldName=COUNTRY_CODE;dbFieldPosition=7;\"},{\"name\":\"regionCode\",\"type\":[\"long\",\"null\"],\"meta\":\"dbFieldName=REGION_CODE;dbFieldPosition=8;\"},{\"name\":\"phone1\",\"type\":[\"string\",\"null\"],\"meta\":\"dbFieldName=PHONE1;dbFieldPosition=9;\"},{\"name\":\"phone2\",\"type\":[\"string\",\"null\"],\"meta\":\"dbFieldName=PHONE2;dbFieldPosition=10;\"},{\"name\":\"fax\",\"type\":[\"string\",\"null\"],\"meta\":\"dbFieldName=FAX;dbFieldPosition=11;\"},{\"name\":\"hq\",\"type\":[\"long\",\"null\"],\"meta\":\"dbFieldName=HQ;dbFieldPosition=12;\"},{\"name\":\"active\",\"type\":[\"string\",\"null\"],\"meta\":\"dbFieldName=ACTIVE;dbFieldPosition=13;\"}],\"meta\":\"dbFieldName=COMPANY_LOCATIONS;dbFieldPosition=0;\"}");
  public java.lang.Long companyLocationId;
  public java.lang.Long companyId;
  public java.lang.CharSequence street1;
  public java.lang.CharSequence street2;
  public java.lang.CharSequence city;
  public java.lang.CharSequence state;
  public java.lang.CharSequence postalCode;
  public java.lang.CharSequence countryCode;
  public java.lang.Long regionCode;
  public java.lang.CharSequence phone1;
  public java.lang.CharSequence phone2;
  public java.lang.CharSequence fax;
  public java.lang.Long hq;
  public java.lang.CharSequence active;
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return companyLocationId;
    case 1: return companyId;
    case 2: return street1;
    case 3: return street2;
    case 4: return city;
    case 5: return state;
    case 6: return postalCode;
    case 7: return countryCode;
    case 8: return regionCode;
    case 9: return phone1;
    case 10: return phone2;
    case 11: return fax;
    case 12: return hq;
    case 13: return active;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: companyLocationId = (java.lang.Long)value$; break;
    case 1: companyId = (java.lang.Long)value$; break;
    case 2: street1 = (java.lang.CharSequence)value$; break;
    case 3: street2 = (java.lang.CharSequence)value$; break;
    case 4: city = (java.lang.CharSequence)value$; break;
    case 5: state = (java.lang.CharSequence)value$; break;
    case 6: postalCode = (java.lang.CharSequence)value$; break;
    case 7: countryCode = (java.lang.CharSequence)value$; break;
    case 8: regionCode = (java.lang.Long)value$; break;
    case 9: phone1 = (java.lang.CharSequence)value$; break;
    case 10: phone2 = (java.lang.CharSequence)value$; break;
    case 11: fax = (java.lang.CharSequence)value$; break;
    case 12: hq = (java.lang.Long)value$; break;
    case 13: active = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
}
