/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.linkedin.events.company;

@SuppressWarnings("all")
/** Auto-generated Avro schema for SY$FLAGGING. Generated at Jun 25, 2012 11:21:28 AM PDT */
public class Flagging_V1 extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = org.apache.avro.Schema.parse("{\"type\":\"record\",\"name\":\"Flagging_V1\",\"namespace\":\"com.linkedin.events.company\",\"fields\":[{\"name\":\"txn\",\"type\":[\"long\",\"null\"],\"meta\":\"dbFieldName=TXN;dbFieldPosition=0;\"},{\"name\":\"key\",\"type\":[\"long\",\"null\"],\"meta\":\"dbFieldName=KEY;dbFieldPosition=1;\"},{\"name\":\"memberId\",\"type\":[\"long\",\"null\"],\"meta\":\"dbFieldName=MEMBER_ID;dbFieldPosition=2;\"},{\"name\":\"entityId\",\"type\":[\"long\",\"null\"],\"meta\":\"dbFieldName=ENTITY_ID;dbFieldPosition=3;\"},{\"name\":\"entityType\",\"type\":[\"string\",\"null\"],\"meta\":\"dbFieldName=ENTITY_TYPE;dbFieldPosition=4;\"},{\"name\":\"description\",\"type\":[\"string\",\"null\"],\"meta\":\"dbFieldName=DESCRIPTION;dbFieldPosition=5;\"},{\"name\":\"creationTime\",\"type\":[\"long\",\"null\"],\"meta\":\"dbFieldName=CREATION_TIME;dbFieldPosition=6;\"},{\"name\":\"status\",\"type\":[\"string\",\"null\"],\"meta\":\"dbFieldName=STATUS;dbFieldPosition=7;\"},{\"name\":\"lastModifiedTime\",\"type\":[\"long\",\"null\"],\"meta\":\"dbFieldName=LAST_MODIFIED_TIME;dbFieldPosition=8;\"}],\"meta\":\"dbFieldName=SY$FLAGGING;\"}");
  public java.lang.Long txn;
  public java.lang.Long key;
  public java.lang.Long memberId;
  public java.lang.Long entityId;
  public java.lang.CharSequence entityType;
  public java.lang.CharSequence description;
  public java.lang.Long creationTime;
  public java.lang.CharSequence status;
  public java.lang.Long lastModifiedTime;
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return txn;
    case 1: return key;
    case 2: return memberId;
    case 3: return entityId;
    case 4: return entityType;
    case 5: return description;
    case 6: return creationTime;
    case 7: return status;
    case 8: return lastModifiedTime;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: txn = (java.lang.Long)value$; break;
    case 1: key = (java.lang.Long)value$; break;
    case 2: memberId = (java.lang.Long)value$; break;
    case 3: entityId = (java.lang.Long)value$; break;
    case 4: entityType = (java.lang.CharSequence)value$; break;
    case 5: description = (java.lang.CharSequence)value$; break;
    case 6: creationTime = (java.lang.Long)value$; break;
    case 7: status = (java.lang.CharSequence)value$; break;
    case 8: lastModifiedTime = (java.lang.Long)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
}
