/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.linkedin.events.company;

@SuppressWarnings("all")
/** Auto-generated Avro schema for SY$PRODUCTS. Generated at Jun 21, 2012 11:39:14 PM PDT */
public class Products_V1 extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = org.apache.avro.Schema.parse("{\"type\":\"record\",\"name\":\"Products_V1\",\"namespace\":\"com.linkedin.events.company\",\"fields\":[{\"name\":\"txn\",\"type\":[\"long\",\"null\"],\"meta\":\"dbFieldName=TXN;dbFieldPosition=0;\"},{\"name\":\"key\",\"type\":[\"long\",\"null\"],\"meta\":\"dbFieldName=KEY;dbFieldPosition=1;\"},{\"name\":\"productId\",\"type\":[\"long\",\"null\"],\"meta\":\"dbFieldName=PRODUCT_ID;dbFieldPosition=2;\"},{\"name\":\"companyId\",\"type\":[\"long\",\"null\"],\"meta\":\"dbFieldName=COMPANY_ID;dbFieldPosition=3;\"},{\"name\":\"productName\",\"type\":[\"string\",\"null\"],\"meta\":\"dbFieldName=PRODUCT_NAME;dbFieldPosition=4;\"},{\"name\":\"productType\",\"type\":[\"string\",\"null\"],\"meta\":\"dbFieldName=PRODUCT_TYPE;dbFieldPosition=5;\"},{\"name\":\"createdDate\",\"type\":[\"long\",\"null\"],\"meta\":\"dbFieldName=CREATED_DATE;dbFieldPosition=6;\"},{\"name\":\"status\",\"type\":[\"string\",\"null\"],\"meta\":\"dbFieldName=STATUS;dbFieldPosition=7;\"},{\"name\":\"data\",\"type\":[\"string\",\"null\"],\"meta\":\"dbFieldName=DATA;dbFieldPosition=8;\"},{\"name\":\"productDv\",\"type\":[\"long\",\"null\"],\"meta\":\"dbFieldName=PRODUCT_DV;dbFieldPosition=9;\"},{\"name\":\"productSv\",\"type\":[\"long\",\"null\"],\"meta\":\"dbFieldName=PRODUCT_SV;dbFieldPosition=10;\"},{\"name\":\"changesetId\",\"type\":[\"long\",\"null\"],\"meta\":\"dbFieldName=CHANGESET_ID;dbFieldPosition=11;\"},{\"name\":\"lastEditorId\",\"type\":[\"long\",\"null\"],\"meta\":\"dbFieldName=LAST_EDITOR_ID;dbFieldPosition=12;\"},{\"name\":\"lastEditedDate\",\"type\":[\"long\",\"null\"],\"meta\":\"dbFieldName=LAST_EDITED_DATE;dbFieldPosition=13;\"}],\"meta\":\"dbFieldName=SY$PRODUCTS;\"}");
  public java.lang.Long txn;
  public java.lang.Long key;
  public java.lang.Long productId;
  public java.lang.Long companyId;
  public java.lang.CharSequence productName;
  public java.lang.CharSequence productType;
  public java.lang.Long createdDate;
  public java.lang.CharSequence status;
  public java.lang.CharSequence data;
  public java.lang.Long productDv;
  public java.lang.Long productSv;
  public java.lang.Long changesetId;
  public java.lang.Long lastEditorId;
  public java.lang.Long lastEditedDate;
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return txn;
    case 1: return key;
    case 2: return productId;
    case 3: return companyId;
    case 4: return productName;
    case 5: return productType;
    case 6: return createdDate;
    case 7: return status;
    case 8: return data;
    case 9: return productDv;
    case 10: return productSv;
    case 11: return changesetId;
    case 12: return lastEditorId;
    case 13: return lastEditedDate;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: txn = (java.lang.Long)value$; break;
    case 1: key = (java.lang.Long)value$; break;
    case 2: productId = (java.lang.Long)value$; break;
    case 3: companyId = (java.lang.Long)value$; break;
    case 4: productName = (java.lang.CharSequence)value$; break;
    case 5: productType = (java.lang.CharSequence)value$; break;
    case 6: createdDate = (java.lang.Long)value$; break;
    case 7: status = (java.lang.CharSequence)value$; break;
    case 8: data = (java.lang.CharSequence)value$; break;
    case 9: productDv = (java.lang.Long)value$; break;
    case 10: productSv = (java.lang.Long)value$; break;
    case 11: changesetId = (java.lang.Long)value$; break;
    case 12: lastEditorId = (java.lang.Long)value$; break;
    case 13: lastEditedDate = (java.lang.Long)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
}
