#! /usr/bin/perl

use DBI;
use Getopt::Long;
use Time::HiRes qw(time);

my $mysql_user = "root";
my $mysql_pw = "";
my $mysql_db = "es_BizProfile_10";
my $table = "BizCompany";
my $mysql_host = "127.0.0.1";
my $num_tries = 10000;

my $dsn = "DBI:mysql:database=$mysql_db;host=$mysql_host";

my $con = DBI->connect($dsn, $mysql_user, $mysql_pw);

die "Error connecting to MySQL\n" unless $con;

my $i;
my $start_ts = time;

for ($i = 0; $i < $num_tries; $i++)
{
  my $ts = sprintf("%d", time * 1000);
  $con->do("update $table set timestamp = $ts limit 1") or 
    die "Error updating $table\n";
}

my $run_time = time - $start_ts;

if ($run_time > 0)
{
  printf("Test executed in %.3f s, %d queries per second\n", $run_time,
    $num_tries/$run_time);
}  