/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.linkedin.events.collab;

@SuppressWarnings("all")
/** Auto-generated Avro schema for sy$MEMBER_DATA. Generated at Aug 31, 2012 11:44:10 AM PDT */
public class MemberData_V1 extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = org.apache.avro.Schema.parse("{\"type\":\"record\",\"name\":\"MemberData_V1\",\"namespace\":\"com.linkedin.events.collab\",\"fields\":[{\"name\":\"txn\",\"type\":[\"long\",\"null\"],\"meta\":\"dbFieldName=TXN;dbFieldPosition=0;\"},{\"name\":\"key\",\"type\":[\"long\",\"null\"],\"meta\":\"dbFieldName=KEY;dbFieldPosition=1;\"},{\"name\":\"memberId\",\"type\":[\"long\",\"null\"],\"meta\":\"dbFieldName=MEMBER_ID;dbFieldPosition=2;\"},{\"name\":\"numConnections\",\"type\":[\"long\",\"null\"],\"meta\":\"dbFieldName=NUM_CONNECTIONS;dbFieldPosition=3;\"},{\"name\":\"state\",\"type\":[\"long\",\"null\"],\"meta\":\"dbFieldName=STATE;dbFieldPosition=4;\"},{\"name\":\"lastUpdated\",\"type\":[\"long\",\"null\"],\"meta\":\"dbFieldName=LAST_UPDATED;dbFieldPosition=5;\"}],\"meta\":\"dbFieldName=sy$MEMBER_DATA;\"}");
  public java.lang.Long txn;
  public java.lang.Long key;
  public java.lang.Long memberId;
  public java.lang.Long numConnections;
  public java.lang.Long state;
  public java.lang.Long lastUpdated;
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return txn;
    case 1: return key;
    case 2: return memberId;
    case 3: return numConnections;
    case 4: return state;
    case 5: return lastUpdated;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: txn = (java.lang.Long)value$; break;
    case 1: key = (java.lang.Long)value$; break;
    case 2: memberId = (java.lang.Long)value$; break;
    case 3: numConnections = (java.lang.Long)value$; break;
    case 4: state = (java.lang.Long)value$; break;
    case 5: lastUpdated = (java.lang.Long)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
}
