/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.linkedin.events.collab;

@SuppressWarnings("all")
/** Auto-generated Avro schema for sy$TEAM_RELATIONSHIPS. Generated at Aug 31, 2012 11:44:08 AM PDT */
public class TeamRelationships_V1 extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = org.apache.avro.Schema.parse("{\"type\":\"record\",\"name\":\"TeamRelationships_V1\",\"namespace\":\"com.linkedin.events.collab\",\"fields\":[{\"name\":\"txn\",\"type\":[\"long\",\"null\"],\"meta\":\"dbFieldName=TXN;dbFieldPosition=0;\"},{\"name\":\"key\",\"type\":[\"long\",\"null\"],\"meta\":\"dbFieldName=KEY;dbFieldPosition=1;\"},{\"name\":\"teamId\",\"type\":[\"long\",\"null\"],\"meta\":\"dbFieldName=TEAM_ID;dbFieldPosition=2;\"},{\"name\":\"sourceUrn\",\"type\":[\"string\",\"null\"],\"meta\":\"dbFieldName=SOURCE_URN;dbFieldPosition=3;\"},{\"name\":\"relationshipType\",\"type\":[\"long\",\"null\"],\"meta\":\"dbFieldName=RELATIONSHIP_TYPE;dbFieldPosition=4;\"},{\"name\":\"relationshipState\",\"type\":[\"long\",\"null\"],\"meta\":\"dbFieldName=RELATIONSHIP_STATE;dbFieldPosition=5;\"},{\"name\":\"version\",\"type\":[\"long\",\"null\"],\"meta\":\"dbFieldName=VERSION;dbFieldPosition=6;\"},{\"name\":\"relationshipData\",\"type\":[\"string\",\"null\"],\"meta\":\"dbFieldName=RELATIONSHIP_DATA;dbFieldPosition=7;\"}],\"meta\":\"dbFieldName=sy$TEAM_RELATIONSHIPS;\"}");
  public java.lang.Long txn;
  public java.lang.Long key;
  public java.lang.Long teamId;
  public java.lang.CharSequence sourceUrn;
  public java.lang.Long relationshipType;
  public java.lang.Long relationshipState;
  public java.lang.Long version;
  public java.lang.CharSequence relationshipData;
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return txn;
    case 1: return key;
    case 2: return teamId;
    case 3: return sourceUrn;
    case 4: return relationshipType;
    case 5: return relationshipState;
    case 6: return version;
    case 7: return relationshipData;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: txn = (java.lang.Long)value$; break;
    case 1: key = (java.lang.Long)value$; break;
    case 2: teamId = (java.lang.Long)value$; break;
    case 3: sourceUrn = (java.lang.CharSequence)value$; break;
    case 4: relationshipType = (java.lang.Long)value$; break;
    case 5: relationshipState = (java.lang.Long)value$; break;
    case 6: version = (java.lang.Long)value$; break;
    case 7: relationshipData = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
}
