/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.linkedin.events.sdr;

@SuppressWarnings("all")
public class databusSdrAnetMbrT extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = org.apache.avro.Schema.parse("{\"type\":\"record\",\"name\":\"databusSdrAnetMbrT\",\"namespace\":\"com.linkedin.events.sdr\",\"fields\":[{\"name\":\"membershipId\",\"type\":[\"int\",\"null\"],\"meta\":\"dbFieldName=MEMBERSHIP_ID;dbFieldPosition=0;\"},{\"name\":\"anetId\",\"type\":[\"int\",\"null\"],\"meta\":\"dbFieldName=ANET_ID;dbFieldPosition=1;\"},{\"name\":\"anetIdType\",\"type\":[\"string\",\"null\"],\"meta\":\"dbFieldName=ANET_ID_TYPE;dbFieldPosition=2;\"},{\"name\":\"isPrimaryAnet\",\"type\":[\"string\",\"null\"],\"meta\":\"dbFieldName=IS_PRIMARY_ANET;dbFieldPosition=3;\"},{\"name\":\"state\",\"type\":[\"string\",\"null\"],\"meta\":\"dbFieldName=STATE;dbFieldPosition=4;\"},{\"name\":\"currency\",\"type\":[\"string\",\"null\"],\"meta\":\"dbFieldName=CURRENCY;dbFieldPosition=5;\"},{\"name\":\"currencyLock\",\"type\":[\"string\",\"null\"],\"meta\":\"dbFieldName=CURRENCY_LOCK;dbFieldPosition=6;\"},{\"name\":\"startDate\",\"type\":[\"int\",\"null\"],\"meta\":\"dbFieldName=START_DATE;dbFieldPosition=7;\"},{\"name\":\"endDate\",\"type\":[\"int\",\"null\"],\"meta\":\"dbFieldName=END_DATE;dbFieldPosition=8;\"},{\"name\":\"createdAt\",\"type\":[\"long\",\"null\"],\"meta\":\"dbFieldName=CREATED_AT;dbFieldPosition=9;\"},{\"name\":\"updatedAt\",\"type\":[\"long\",\"null\"],\"meta\":\"dbFieldName=UPDATED_AT;dbFieldPosition=10;\"}],\"meta\":\"dbFieldName=MEMBER_ANET_IDS;dbFieldPosition=25;\"}");
  public java.lang.Integer membershipId;
  public java.lang.Integer anetId;
  public java.lang.CharSequence anetIdType;
  public java.lang.CharSequence isPrimaryAnet;
  public java.lang.CharSequence state;
  public java.lang.CharSequence currency;
  public java.lang.CharSequence currencyLock;
  public java.lang.Integer startDate;
  public java.lang.Integer endDate;
  public java.lang.Long createdAt;
  public java.lang.Long updatedAt;
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return membershipId;
    case 1: return anetId;
    case 2: return anetIdType;
    case 3: return isPrimaryAnet;
    case 4: return state;
    case 5: return currency;
    case 6: return currencyLock;
    case 7: return startDate;
    case 8: return endDate;
    case 9: return createdAt;
    case 10: return updatedAt;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: membershipId = (java.lang.Integer)value$; break;
    case 1: anetId = (java.lang.Integer)value$; break;
    case 2: anetIdType = (java.lang.CharSequence)value$; break;
    case 3: isPrimaryAnet = (java.lang.CharSequence)value$; break;
    case 4: state = (java.lang.CharSequence)value$; break;
    case 5: currency = (java.lang.CharSequence)value$; break;
    case 6: currencyLock = (java.lang.CharSequence)value$; break;
    case 7: startDate = (java.lang.Integer)value$; break;
    case 8: endDate = (java.lang.Integer)value$; break;
    case 9: createdAt = (java.lang.Long)value$; break;
    case 10: updatedAt = (java.lang.Long)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
}
