/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.linkedin.events.member2.setting;

@SuppressWarnings("all")
/** Auto-generated Avro schema for SY$MEMBER_SETTING. Generated at Feb 10, 2012 05:37:00 PM PST */
public class MemberSetting_V2 extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = org.apache.avro.Schema.parse("{\"type\":\"record\",\"name\":\"MemberSetting_V2\",\"namespace\":\"com.linkedin.events.member2.setting\",\"fields\":[{\"name\":\"txn\",\"type\":[\"long\",\"null\"],\"meta\":\"dbFieldName=TXN;dbFieldPosition=0;\"},{\"name\":\"key\",\"type\":[\"string\",\"null\"],\"meta\":\"dbFieldName=KEY;dbFieldPosition=1;\"},{\"name\":\"settingId\",\"type\":[\"long\",\"null\"],\"meta\":\"dbFieldName=SETTING_ID;dbFieldPosition=2;\"},{\"name\":\"memberId\",\"type\":[\"long\",\"null\"],\"meta\":\"dbFieldName=MEMBER_ID;dbFieldPosition=3;\"},{\"name\":\"settingValue\",\"type\":[\"string\",\"null\"],\"meta\":\"dbFieldName=SETTING_VALUE;dbFieldPosition=4;\"},{\"name\":\"dateCreated\",\"type\":[\"long\",\"null\"],\"meta\":\"dbFieldName=DATE_CREATED;dbFieldPosition=5;\"},{\"name\":\"dateModified\",\"type\":[\"long\",\"null\"],\"meta\":\"dbFieldName=DATE_MODIFIED;dbFieldPosition=6;\"}],\"meta\":\"dbFieldName=SY$MEMBER_SETTING;\"}");
  public java.lang.Long txn;
  public java.lang.CharSequence key;
  public java.lang.Long settingId;
  public java.lang.Long memberId;
  public java.lang.CharSequence settingValue;
  public java.lang.Long dateCreated;
  public java.lang.Long dateModified;
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return txn;
    case 1: return key;
    case 2: return settingId;
    case 3: return memberId;
    case 4: return settingValue;
    case 5: return dateCreated;
    case 6: return dateModified;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: txn = (java.lang.Long)value$; break;
    case 1: key = (java.lang.CharSequence)value$; break;
    case 2: settingId = (java.lang.Long)value$; break;
    case 3: memberId = (java.lang.Long)value$; break;
    case 4: settingValue = (java.lang.CharSequence)value$; break;
    case 5: dateCreated = (java.lang.Long)value$; break;
    case 6: dateModified = (java.lang.Long)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
}
