#! /usr/bin/perl

my $i = 0;
my $NUM_DBS = 1000;

if ($#ARGV >= 0)
{
  $NUM_DBS = $ARGV[0];
}

my $q = "select binlog_undo_batch(";

for ($i = 1; $i <= $NUM_DBS; $i++)
{
  $q .= "," if ($i > 1);
  $q .= "'db$i',$i,$i";
}

$q .= ");";

print "$q\n";

