#! /usr/bin/perl

use Getopt::Long;

my $conf_dir =  $ENV{HOME}.
  "/databus2/build/databus2-relay-cmdline-pkg/distributions/conf";

my $start_part_id = 381;
my $num_parts = 5;
my $start_src_id = 100;

sub bail
{
  my ($msg) = @_;
  print "$msg\n";
  exit 1;
}

sub write_part_json
{
  my ($part_id,$src_id) = @_;
  open FH, ">$conf_dir/$part_id.json";
print FH <<EOT;
{
    "name" : "es_emailtest_$part_id",
    "id"  : $part_id,
    "uri" : "localhost",
     "slowSourceQueryThreshold" : 2000,
     "maxSCNHandler": {
        "type": "FILE",
        "file": {"scnDir": "logs/binlog_ofs"}
     },
     "sources" :
        [
                {"id" : $src_id,
                 "name" : "emailtest.t1",
                 "uri": "emailtest.t1",
                 "partitionFunction" : "constant:1",
                 "partition" : $part_id
                }
        ]
}

EOT
  
  close FH;
}

bail("Invalid option syntax") unless 
 GetOptions("conf-dir=s" => \$conf_dir,
            "start-part-id=i" => \$start_part_id,
            "start-src-id=i" => \$start_src_id,
            "num-parts=i" => \$num_parts );

my $i;

for ($i = 0; $i < $num_parts; $i++)
{
  write_part_json($start_part_id + $i, $start_src_id + $i);
}