/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.linkedin.events.leo;
/*
 *
 * Copyright 2013 LinkedIn Corp. All rights reserved
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 *
*/


@SuppressWarnings("all")
/** Auto-generated Avro schema for leo2.sy$experts_1. Generated at Sep 15, 2011 09:53:33 AM PDT */
public class Experts_V1 extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = org.apache.avro.Schema.parse("{\"type\":\"record\",\"name\":\"Experts_V1\",\"namespace\":\"com.linkedin.events.leo\",\"fields\":[{\"name\":\"txn\",\"type\":[\"int\",\"null\"],\"meta\":\"dbFieldName=TXN;dbFieldPosition=0;\"},{\"name\":\"key\",\"type\":[\"int\",\"null\"],\"meta\":\"dbFieldName=KEY;dbFieldPosition=1;\"},{\"name\":\"expertiseId\",\"type\":[\"int\",\"null\"],\"meta\":\"dbFieldName=EXPERTISE_ID;dbFieldPosition=2;\"},{\"name\":\"memberId\",\"type\":[\"int\",\"null\"],\"meta\":\"dbFieldName=MEMBER_ID;dbFieldPosition=3;\"},{\"name\":\"cat\",\"type\":[\"string\",\"null\"],\"meta\":\"dbFieldName=CAT;dbFieldPosition=4;\"},{\"name\":\"numGoodAnswers\",\"type\":[\"int\",\"null\"],\"meta\":\"dbFieldName=NUM_GOOD_ANSWERS;dbFieldPosition=5;\"},{\"name\":\"numBestAnswers\",\"type\":[\"int\",\"null\"],\"meta\":\"dbFieldName=NUM_BEST_ANSWERS;dbFieldPosition=6;\"},{\"name\":\"locales\",\"type\":[\"string\",\"null\"],\"meta\":\"dbFieldName=LOCALES;dbFieldPosition=7;\"}],\"meta\":\"dbFieldName=leo2.sy$experts_1;\"}");
  public java.lang.Integer txn;
  public java.lang.Integer key;
  public java.lang.Integer expertiseId;
  public java.lang.Integer memberId;
  public java.lang.CharSequence cat;
  public java.lang.Integer numGoodAnswers;
  public java.lang.Integer numBestAnswers;
  public java.lang.CharSequence locales;
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return txn;
    case 1: return key;
    case 2: return expertiseId;
    case 3: return memberId;
    case 4: return cat;
    case 5: return numGoodAnswers;
    case 6: return numBestAnswers;
    case 7: return locales;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: txn = (java.lang.Integer)value$; break;
    case 1: key = (java.lang.Integer)value$; break;
    case 2: expertiseId = (java.lang.Integer)value$; break;
    case 3: memberId = (java.lang.Integer)value$; break;
    case 4: cat = (java.lang.CharSequence)value$; break;
    case 5: numGoodAnswers = (java.lang.Integer)value$; break;
    case 6: numBestAnswers = (java.lang.Integer)value$; break;
    case 7: locales = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
}
