/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.linkedin.events.eos;

@SuppressWarnings("all")
/** Auto-generated Avro schema for eos.sy$member_emails. Generated at Sep 15, 2011 11:59:19 AM PDT */
public class MemberEmails_V1 extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = org.apache.avro.Schema.parse("{\"type\":\"record\",\"name\":\"MemberEmails_V1\",\"namespace\":\"com.linkedin.events.eos\",\"fields\":[{\"name\":\"txn\",\"type\":[\"int\",\"null\"],\"meta\":\"dbFieldName=TXN;dbFieldPosition=0;\"},{\"name\":\"key\",\"type\":[\"int\",\"null\"],\"meta\":\"dbFieldName=KEY;dbFieldPosition=1;\"},{\"name\":\"emailId\",\"type\":[\"int\",\"null\"],\"meta\":\"dbFieldName=EMAIL_ID;dbFieldPosition=2;\"},{\"name\":\"email\",\"type\":[\"string\",\"null\"],\"meta\":\"dbFieldName=EMAIL;dbFieldPosition=3;\"},{\"name\":\"memberId\",\"type\":[\"int\",\"null\"],\"meta\":\"dbFieldName=MEMBER_ID;dbFieldPosition=4;\"},{\"name\":\"isPrimary\",\"type\":[\"int\",\"null\"],\"meta\":\"dbFieldName=IS_PRIMARY;dbFieldPosition=5;\"},{\"name\":\"isConfirmed\",\"type\":[\"string\",\"null\"],\"meta\":\"dbFieldName=IS_CONFIRMED;dbFieldPosition=6;\"}],\"meta\":\"dbFieldName=eos.sy$member_emails;\"}");
  public java.lang.Integer txn;
  public java.lang.Integer key;
  public java.lang.Integer emailId;
  public java.lang.CharSequence email;
  public java.lang.Integer memberId;
  public java.lang.Integer isPrimary;
  public java.lang.CharSequence isConfirmed;
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return txn;
    case 1: return key;
    case 2: return emailId;
    case 3: return email;
    case 4: return memberId;
    case 5: return isPrimary;
    case 6: return isConfirmed;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: txn = (java.lang.Integer)value$; break;
    case 1: key = (java.lang.Integer)value$; break;
    case 2: emailId = (java.lang.Integer)value$; break;
    case 3: email = (java.lang.CharSequence)value$; break;
    case 4: memberId = (java.lang.Integer)value$; break;
    case 5: isPrimary = (java.lang.Integer)value$; break;
    case 6: isConfirmed = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
}
