/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.linkedin.events.eos;
/*
 *
 * Copyright 2013 LinkedIn Corp. All rights reserved
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 *
*/


@SuppressWarnings("all")
/** Auto-generated Avro schema for sy$member_emails. Generated at Oct 15, 2012 03:55:08 PM PDT */
public class MemberEmails_V2 extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = org.apache.avro.Schema.parse("{\"type\":\"record\",\"name\":\"MemberEmails_V2\",\"namespace\":\"com.linkedin.events.eos\",\"fields\":[{\"name\":\"txn\",\"type\":[\"long\",\"null\"],\"meta\":\"dbFieldName=TXN;dbFieldPosition=0;\"},{\"name\":\"key\",\"type\":[\"long\",\"null\"],\"meta\":\"dbFieldName=KEY;dbFieldPosition=1;\"},{\"name\":\"emailId\",\"type\":[\"long\",\"null\"],\"meta\":\"dbFieldName=EMAIL_ID;dbFieldPosition=2;\"},{\"name\":\"email\",\"type\":[\"string\",\"null\"],\"meta\":\"dbFieldName=EMAIL;dbFieldPosition=3;\"},{\"name\":\"memberId\",\"type\":[\"long\",\"null\"],\"meta\":\"dbFieldName=MEMBER_ID;dbFieldPosition=4;\"},{\"name\":\"isPrimary\",\"type\":[\"long\",\"null\"],\"meta\":\"dbFieldName=IS_PRIMARY;dbFieldPosition=5;\"},{\"name\":\"isConfirmed\",\"type\":[\"string\",\"null\"],\"meta\":\"dbFieldName=IS_CONFIRMED;dbFieldPosition=6;\"}],\"meta\":\"dbFieldName=sy$member_emails;\"}");
  public java.lang.Long txn;
  public java.lang.Long key;
  public java.lang.Long emailId;
  public java.lang.CharSequence email;
  public java.lang.Long memberId;
  public java.lang.Long isPrimary;
  public java.lang.CharSequence isConfirmed;
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return txn;
    case 1: return key;
    case 2: return emailId;
    case 3: return email;
    case 4: return memberId;
    case 5: return isPrimary;
    case 6: return isConfirmed;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: txn = (java.lang.Long)value$; break;
    case 1: key = (java.lang.Long)value$; break;
    case 2: emailId = (java.lang.Long)value$; break;
    case 3: email = (java.lang.CharSequence)value$; break;
    case 4: memberId = (java.lang.Long)value$; break;
    case 5: isPrimary = (java.lang.Long)value$; break;
    case 6: isConfirmed = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
}
