/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.linkedin.events.conns;

@SuppressWarnings("all")
/** Auto-generated Avro schema for conns.sy$connections_cnt. Generated at Sep 15, 2011 09:42:49 AM PDT */
public class ConnectionsCnt_V1 extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = org.apache.avro.Schema.parse("{\"type\":\"record\",\"name\":\"ConnectionsCnt_V1\",\"namespace\":\"com.linkedin.events.conns\",\"fields\":[{\"name\":\"txn\",\"type\":[\"int\",\"null\"],\"meta\":\"dbFieldName=TXN;dbFieldPosition=0;\"},{\"name\":\"key\",\"type\":[\"string\",\"null\"],\"meta\":\"dbFieldName=KEY;dbFieldPosition=1;\"},{\"name\":\"memberId\",\"type\":[\"int\",\"null\"],\"meta\":\"dbFieldName=MEMBER_ID;dbFieldPosition=2;\"},{\"name\":\"cnt\",\"type\":[\"int\",\"null\"],\"meta\":\"dbFieldName=CNT;dbFieldPosition=3;\"}],\"meta\":\"dbFieldName=conns.sy$connections_cnt;\"}");
  public java.lang.Integer txn;
  public java.lang.CharSequence key;
  public java.lang.Integer memberId;
  public java.lang.Integer cnt;
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return txn;
    case 1: return key;
    case 2: return memberId;
    case 3: return cnt;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: txn = (java.lang.Integer)value$; break;
    case 1: key = (java.lang.CharSequence)value$; break;
    case 2: memberId = (java.lang.Integer)value$; break;
    case 3: cnt = (java.lang.Integer)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
}
