/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.linkedin.events.company;

@SuppressWarnings("all")
public class companyDescriptionT extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = org.apache.avro.Schema.parse("{\"type\":\"record\",\"name\":\"companyDescriptionT\",\"namespace\":\"com.linkedin.events.company\",\"fields\":[{\"name\":\"crudType\",\"type\":[\"string\",\"null\"],\"meta\":\"dbFieldName=CRUD_TYPE;dbFieldPosition=0;\"},{\"name\":\"descriptionId\",\"type\":[\"long\",\"null\"],\"meta\":\"dbFieldName=DESCRIPTION_ID;dbFieldPosition=1;\"},{\"name\":\"companyId\",\"type\":[\"long\",\"null\"],\"meta\":\"dbFieldName=COMPANY_ID;dbFieldPosition=2;\"},{\"name\":\"description\",\"type\":[\"string\",\"null\"],\"meta\":\"dbFieldName=DESCRIPTION;dbFieldPosition=3;\"},{\"name\":\"locale\",\"type\":[\"string\",\"null\"],\"meta\":\"dbFieldName=LOCALE;dbFieldPosition=4;\"},{\"name\":\"changesetId\",\"type\":[\"long\",\"null\"],\"meta\":\"dbFieldName=CHANGESET_ID;dbFieldPosition=5;\"}],\"meta\":\"dbFieldName=COMPANY_DESCRIPTIONS;dbFieldPosition=0;\"}");
  public java.lang.CharSequence crudType;
  public java.lang.Long descriptionId;
  public java.lang.Long companyId;
  public java.lang.CharSequence description;
  public java.lang.CharSequence locale;
  public java.lang.Long changesetId;
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return crudType;
    case 1: return descriptionId;
    case 2: return companyId;
    case 3: return description;
    case 4: return locale;
    case 5: return changesetId;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: crudType = (java.lang.CharSequence)value$; break;
    case 1: descriptionId = (java.lang.Long)value$; break;
    case 2: companyId = (java.lang.Long)value$; break;
    case 3: description = (java.lang.CharSequence)value$; break;
    case 4: locale = (java.lang.CharSequence)value$; break;
    case 5: changesetId = (java.lang.Long)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
}
