/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.linkedin.events.company;

@SuppressWarnings("all")
/** Auto-generated Avro schema for sy$company_fbpages. Generated at Nov 29, 2012 12:35:27 PM PST */
public class CompanyFBPages_V1 extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = org.apache.avro.Schema.parse("{\"type\":\"record\",\"name\":\"CompanyFBPages_V1\",\"namespace\":\"com.linkedin.events.company\",\"fields\":[{\"name\":\"txn\",\"type\":[\"long\",\"null\"],\"meta\":\"dbFieldName=TXN;dbFieldPosition=0;\"},{\"name\":\"key\",\"type\":[\"long\",\"null\"],\"meta\":\"dbFieldName=KEY;dbFieldPosition=1;\"},{\"name\":\"pageId\",\"type\":[\"string\",\"null\"],\"meta\":\"dbFieldName=PAGE_ID;dbFieldPosition=2;\"},{\"name\":\"entityType\",\"type\":[\"string\",\"null\"],\"meta\":\"dbFieldName=ENTITY_TYPE;dbFieldPosition=3;\"},{\"name\":\"data\",\"type\":[\"string\",\"null\"],\"meta\":\"dbFieldName=DATA;dbFieldPosition=4;\"},{\"name\":\"createdDate\",\"type\":[\"long\",\"null\"],\"meta\":\"dbFieldName=CREATED_DATE;dbFieldPosition=5;\"},{\"name\":\"modifiedDate\",\"type\":[\"long\",\"null\"],\"meta\":\"dbFieldName=MODIFIED_DATE;dbFieldPosition=6;\"},{\"name\":\"status\",\"type\":[\"string\",\"null\"],\"meta\":\"dbFieldName=STATUS;dbFieldPosition=7;\"},{\"name\":\"dataVersion\",\"type\":[\"long\",\"null\"],\"meta\":\"dbFieldName=DATA_VERSION;dbFieldPosition=8;\"},{\"name\":\"schemaVersion\",\"type\":[\"long\",\"null\"],\"meta\":\"dbFieldName=SCHEMA_VERSION;dbFieldPosition=9;\"}],\"meta\":\"dbFieldName=sy$company_fbpages;\"}");
  public java.lang.Long txn;
  public java.lang.Long key;
  public java.lang.CharSequence pageId;
  public java.lang.CharSequence entityType;
  public java.lang.CharSequence data;
  public java.lang.Long createdDate;
  public java.lang.Long modifiedDate;
  public java.lang.CharSequence status;
  public java.lang.Long dataVersion;
  public java.lang.Long schemaVersion;
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return txn;
    case 1: return key;
    case 2: return pageId;
    case 3: return entityType;
    case 4: return data;
    case 5: return createdDate;
    case 6: return modifiedDate;
    case 7: return status;
    case 8: return dataVersion;
    case 9: return schemaVersion;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: txn = (java.lang.Long)value$; break;
    case 1: key = (java.lang.Long)value$; break;
    case 2: pageId = (java.lang.CharSequence)value$; break;
    case 3: entityType = (java.lang.CharSequence)value$; break;
    case 4: data = (java.lang.CharSequence)value$; break;
    case 5: createdDate = (java.lang.Long)value$; break;
    case 6: modifiedDate = (java.lang.Long)value$; break;
    case 7: status = (java.lang.CharSequence)value$; break;
    case 8: dataVersion = (java.lang.Long)value$; break;
    case 9: schemaVersion = (java.lang.Long)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
}
