/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.linkedin.events.company;

@SuppressWarnings("all")
public class DATABUS_COMPANY_LOCS_T extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = org.apache.avro.Schema.parse("{\"type\":\"record\",\"name\":\"DATABUS_COMPANY_LOCS_T\",\"namespace\":\"com.linkedin.events.company\",\"fields\":[{\"name\":\"companyLocations\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"databusCompanyLocT\",\"fields\":[{\"name\":\"companyLocationId\",\"type\":[\"long\",\"null\"],\"meta\":\"dbFieldName=COMPANY_LOCATION_ID;dbFieldPosition=0;\"},{\"name\":\"companyId\",\"type\":[\"long\",\"null\"],\"meta\":\"dbFieldName=COMPANY_ID;dbFieldPosition=1;\"},{\"name\":\"street1\",\"type\":[\"string\",\"null\"],\"meta\":\"dbFieldName=STREET1;dbFieldPosition=2;\"},{\"name\":\"street2\",\"type\":[\"string\",\"null\"],\"meta\":\"dbFieldName=STREET2;dbFieldPosition=3;\"},{\"name\":\"city\",\"type\":[\"string\",\"null\"],\"meta\":\"dbFieldName=CITY;dbFieldPosition=4;\"},{\"name\":\"state\",\"type\":[\"string\",\"null\"],\"meta\":\"dbFieldName=STATE;dbFieldPosition=5;\"},{\"name\":\"postalCode\",\"type\":[\"string\",\"null\"],\"meta\":\"dbFieldName=POSTAL_CODE;dbFieldPosition=6;\"},{\"name\":\"countryCode\",\"type\":[\"string\",\"null\"],\"meta\":\"dbFieldName=COUNTRY_CODE;dbFieldPosition=7;\"},{\"name\":\"regionCode\",\"type\":[\"long\",\"null\"],\"meta\":\"dbFieldName=REGION_CODE;dbFieldPosition=8;\"},{\"name\":\"phone1\",\"type\":[\"string\",\"null\"],\"meta\":\"dbFieldName=PHONE1;dbFieldPosition=9;\"},{\"name\":\"phone2\",\"type\":[\"string\",\"null\"],\"meta\":\"dbFieldName=PHONE2;dbFieldPosition=10;\"},{\"name\":\"fax\",\"type\":[\"string\",\"null\"],\"meta\":\"dbFieldName=FAX;dbFieldPosition=11;\"},{\"name\":\"hq\",\"type\":[\"long\",\"null\"],\"meta\":\"dbFieldName=HQ;dbFieldPosition=12;\"},{\"name\":\"active\",\"type\":[\"string\",\"null\"],\"meta\":\"dbFieldName=ACTIVE;dbFieldPosition=13;\"}],\"meta\":\"dbFieldName=COMPANY_LOCATIONS;dbFieldPosition=0;\"}}}]}");
  public java.util.List<com.linkedin.events.company.databusCompanyLocT> companyLocations;
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return companyLocations;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: companyLocations = (java.util.List<com.linkedin.events.company.databusCompanyLocT>)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
}
