/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.linkedin.events.company;
/*
 *
 * Copyright 2013 LinkedIn Corp. All rights reserved
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 *
*/


@SuppressWarnings("all")
public class databusCompanyRelT extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = org.apache.avro.Schema.parse("{\"type\":\"record\",\"name\":\"databusCompanyRelT\",\"namespace\":\"com.linkedin.events.company\",\"fields\":[{\"name\":\"relationshipId\",\"type\":[\"long\",\"null\"],\"meta\":\"dbFieldName=RELATIONSHIP_ID;dbFieldPosition=0;\"},{\"name\":\"companyId\",\"type\":[\"long\",\"null\"],\"meta\":\"dbFieldName=COMPANY_ID;dbFieldPosition=1;\"},{\"name\":\"relatedCompanyId\",\"type\":[\"long\",\"null\"],\"meta\":\"dbFieldName=RELATED_COMPANY_ID;dbFieldPosition=2;\"},{\"name\":\"startDate\",\"type\":[\"long\",\"null\"],\"meta\":\"dbFieldName=START_DATE;dbFieldPosition=3;\"},{\"name\":\"endDate\",\"type\":[\"long\",\"null\"],\"meta\":\"dbFieldName=END_DATE;dbFieldPosition=4;\"},{\"name\":\"relationshipType\",\"type\":[\"string\",\"null\"],\"meta\":\"dbFieldName=RELATIONSHIP_TYPE;dbFieldPosition=5;\"},{\"name\":\"state\",\"type\":[\"string\",\"null\"],\"meta\":\"dbFieldName=STATE;dbFieldPosition=6;\"},{\"name\":\"active\",\"type\":[\"string\",\"null\"],\"meta\":\"dbFieldName=ACTIVE;dbFieldPosition=7;\"}],\"meta\":\"dbFieldName=COMPANY_RELATIONSHIPS;dbFieldPosition=0;\"}");
  public java.lang.Long relationshipId;
  public java.lang.Long companyId;
  public java.lang.Long relatedCompanyId;
  public java.lang.Long startDate;
  public java.lang.Long endDate;
  public java.lang.CharSequence relationshipType;
  public java.lang.CharSequence state;
  public java.lang.CharSequence active;
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return relationshipId;
    case 1: return companyId;
    case 2: return relatedCompanyId;
    case 3: return startDate;
    case 4: return endDate;
    case 5: return relationshipType;
    case 6: return state;
    case 7: return active;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: relationshipId = (java.lang.Long)value$; break;
    case 1: companyId = (java.lang.Long)value$; break;
    case 2: relatedCompanyId = (java.lang.Long)value$; break;
    case 3: startDate = (java.lang.Long)value$; break;
    case 4: endDate = (java.lang.Long)value$; break;
    case 5: relationshipType = (java.lang.CharSequence)value$; break;
    case 6: state = (java.lang.CharSequence)value$; break;
    case 7: active = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
}
