/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.linkedin.events.company;
/*
 *
 * Copyright 2013 LinkedIn Corp. All rights reserved
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 *
*/


@SuppressWarnings("all")
public class DATABUS_COMPANY_RELS_T extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = org.apache.avro.Schema.parse("{\"type\":\"record\",\"name\":\"DATABUS_COMPANY_RELS_T\",\"namespace\":\"com.linkedin.events.company\",\"fields\":[{\"name\":\"companyRelationships\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"databusCompanyRelT\",\"fields\":[{\"name\":\"relationshipId\",\"type\":[\"long\",\"null\"],\"meta\":\"dbFieldName=RELATIONSHIP_ID;dbFieldPosition=0;\"},{\"name\":\"companyId\",\"type\":[\"long\",\"null\"],\"meta\":\"dbFieldName=COMPANY_ID;dbFieldPosition=1;\"},{\"name\":\"relatedCompanyId\",\"type\":[\"long\",\"null\"],\"meta\":\"dbFieldName=RELATED_COMPANY_ID;dbFieldPosition=2;\"},{\"name\":\"startDate\",\"type\":[\"long\",\"null\"],\"meta\":\"dbFieldName=START_DATE;dbFieldPosition=3;\"},{\"name\":\"endDate\",\"type\":[\"long\",\"null\"],\"meta\":\"dbFieldName=END_DATE;dbFieldPosition=4;\"},{\"name\":\"relationshipType\",\"type\":[\"string\",\"null\"],\"meta\":\"dbFieldName=RELATIONSHIP_TYPE;dbFieldPosition=5;\"},{\"name\":\"state\",\"type\":[\"string\",\"null\"],\"meta\":\"dbFieldName=STATE;dbFieldPosition=6;\"},{\"name\":\"active\",\"type\":[\"string\",\"null\"],\"meta\":\"dbFieldName=ACTIVE;dbFieldPosition=7;\"}],\"meta\":\"dbFieldName=COMPANY_RELATIONSHIPS;dbFieldPosition=0;\"}}}]}");
  public java.util.List<com.linkedin.events.company.databusCompanyRelT> companyRelationships;
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return companyRelationships;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: companyRelationships = (java.util.List<com.linkedin.events.company.databusCompanyRelT>)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
}
