/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.linkedin.events.company;

@SuppressWarnings("all")
/** Auto-generated Avro schema for SY$REVIEWS. Generated at Jun 25, 2012 11:20:42 AM PDT */
public class Reviews_V1 extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = org.apache.avro.Schema.parse("{\"type\":\"record\",\"name\":\"Reviews_V1\",\"namespace\":\"com.linkedin.events.company\",\"fields\":[{\"name\":\"txn\",\"type\":[\"long\",\"null\"],\"meta\":\"dbFieldName=TXN;dbFieldPosition=0;\"},{\"name\":\"key\",\"type\":[\"long\",\"null\"],\"meta\":\"dbFieldName=KEY;dbFieldPosition=1;\"},{\"name\":\"reviewId\",\"type\":[\"long\",\"null\"],\"meta\":\"dbFieldName=REVIEW_ID;dbFieldPosition=2;\"},{\"name\":\"entityType\",\"type\":[\"string\",\"null\"],\"meta\":\"dbFieldName=ENTITY_TYPE;dbFieldPosition=3;\"},{\"name\":\"entityId\",\"type\":[\"long\",\"null\"],\"meta\":\"dbFieldName=ENTITY_ID;dbFieldPosition=4;\"},{\"name\":\"reviewerId\",\"type\":[\"long\",\"null\"],\"meta\":\"dbFieldName=REVIEWER_ID;dbFieldPosition=5;\"},{\"name\":\"rating\",\"type\":[\"long\",\"null\"],\"meta\":\"dbFieldName=RATING;dbFieldPosition=6;\"},{\"name\":\"attributes\",\"type\":[\"long\",\"null\"],\"meta\":\"dbFieldName=ATTRIBUTES;dbFieldPosition=7;\"},{\"name\":\"createdDate\",\"type\":[\"long\",\"null\"],\"meta\":\"dbFieldName=CREATED_DATE;dbFieldPosition=8;\"},{\"name\":\"modifiedDate\",\"type\":[\"long\",\"null\"],\"meta\":\"dbFieldName=MODIFIED_DATE;dbFieldPosition=9;\"},{\"name\":\"status\",\"type\":[\"string\",\"null\"],\"meta\":\"dbFieldName=STATUS;dbFieldPosition=10;\"},{\"name\":\"data\",\"type\":[\"string\",\"null\"],\"meta\":\"dbFieldName=DATA;dbFieldPosition=11;\"},{\"name\":\"reviewDv\",\"type\":[\"long\",\"null\"],\"meta\":\"dbFieldName=REVIEW_DV;dbFieldPosition=12;\"},{\"name\":\"reviewSv\",\"type\":[\"long\",\"null\"],\"meta\":\"dbFieldName=REVIEW_SV;dbFieldPosition=13;\"}],\"meta\":\"dbFieldName=SY$REVIEWS;\"}");
  public java.lang.Long txn;
  public java.lang.Long key;
  public java.lang.Long reviewId;
  public java.lang.CharSequence entityType;
  public java.lang.Long entityId;
  public java.lang.Long reviewerId;
  public java.lang.Long rating;
  public java.lang.Long attributes;
  public java.lang.Long createdDate;
  public java.lang.Long modifiedDate;
  public java.lang.CharSequence status;
  public java.lang.CharSequence data;
  public java.lang.Long reviewDv;
  public java.lang.Long reviewSv;
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return txn;
    case 1: return key;
    case 2: return reviewId;
    case 3: return entityType;
    case 4: return entityId;
    case 5: return reviewerId;
    case 6: return rating;
    case 7: return attributes;
    case 8: return createdDate;
    case 9: return modifiedDate;
    case 10: return status;
    case 11: return data;
    case 12: return reviewDv;
    case 13: return reviewSv;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: txn = (java.lang.Long)value$; break;
    case 1: key = (java.lang.Long)value$; break;
    case 2: reviewId = (java.lang.Long)value$; break;
    case 3: entityType = (java.lang.CharSequence)value$; break;
    case 4: entityId = (java.lang.Long)value$; break;
    case 5: reviewerId = (java.lang.Long)value$; break;
    case 6: rating = (java.lang.Long)value$; break;
    case 7: attributes = (java.lang.Long)value$; break;
    case 8: createdDate = (java.lang.Long)value$; break;
    case 9: modifiedDate = (java.lang.Long)value$; break;
    case 10: status = (java.lang.CharSequence)value$; break;
    case 11: data = (java.lang.CharSequence)value$; break;
    case 12: reviewDv = (java.lang.Long)value$; break;
    case 13: reviewSv = (java.lang.Long)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
}
