/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.linkedin.events.gfeed;
/*
 *
 * Copyright 2013 LinkedIn Corp. All rights reserved
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 *
*/


@SuppressWarnings("all")
/** Auto-generated Avro schema for gfeed.sy$efeed_stats_2. Generated at Sep 15, 2011 02:45:18 PM PDT */
public class EFeedStats_V2 extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = org.apache.avro.Schema.parse("{\"type\":\"record\",\"name\":\"EFeedStats_V2\",\"namespace\":\"com.linkedin.events.gfeed\",\"fields\":[{\"name\":\"txn\",\"type\":[\"int\",\"null\"],\"meta\":\"dbFieldName=TXN;dbFieldPosition=0;\"},{\"name\":\"type\",\"type\":[\"string\",\"null\"],\"meta\":\"dbFieldName=TYPE;dbFieldPosition=1;\"},{\"name\":\"id\",\"type\":[\"int\",\"null\"],\"meta\":\"dbFieldName=ID;dbFieldPosition=2;\"},{\"name\":\"updateDate\",\"type\":[\"long\",\"null\"],\"meta\":\"dbFieldName=UPDATE_DATE;dbFieldPosition=3;\"},{\"name\":\"fullSummary\",\"type\":[\"string\",\"null\"],\"meta\":\"dbFieldName=FULL_SUMMARY;dbFieldPosition=4;\"}],\"meta\":\"dbFieldName=gfeed.sy$efeed_stats_2;\"}");
  public java.lang.Integer txn;
  public java.lang.CharSequence type;
  public java.lang.Integer id;
  public java.lang.Long updateDate;
  public java.lang.CharSequence fullSummary;
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return txn;
    case 1: return type;
    case 2: return id;
    case 3: return updateDate;
    case 4: return fullSummary;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: txn = (java.lang.Integer)value$; break;
    case 1: type = (java.lang.CharSequence)value$; break;
    case 2: id = (java.lang.Integer)value$; break;
    case 3: updateDate = (java.lang.Long)value$; break;
    case 4: fullSummary = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
}
