#!/bin/bash

host=$1
src=$2
dest=$3

if [ -z "$host" -o -z "$src" ] ; then
	echo "USAGE: $0 host srcfile [destination]"
fi


ts=`date +'%Y%m%d-%H%M%S'`
fname=`basename $src`
tmp_name=/export/home/$USER/$fname.$host.$ts

if [ -z "$dest" ] ; then
	dest=$fname.$host.$ts
fi

if ( expr match $host '.*\.prod' ) ; then
  ssh -A eng-portal.corp.linkedin.com -t scp $host:$src $tmp_name
  scp eng-portal.corp.linkedin.com:$tmp_name $dest
  ssh -A eng-portal.corp.linkedin.com -t rm $tmp_name
else
  scp $host:$src $dest
fi

