/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.linkedin.events.cappr;

@SuppressWarnings("all")
/** Auto-generated Avro schema for sy$prospect_update. Generated at Jan 21, 2013 11:33:03 AM PST */
public class ProspectUpdate_V1 extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = org.apache.avro.Schema.parse("{\"type\":\"record\",\"name\":\"ProspectUpdate_V1\",\"namespace\":\"com.linkedin.events.cappr\",\"fields\":[{\"name\":\"txn\",\"type\":[\"long\",\"null\"],\"meta\":\"dbFieldName=TXN;dbFieldPosition=0;\"},{\"name\":\"prospectId\",\"type\":[\"long\",\"null\"],\"meta\":\"dbFieldName=PROSPECT_ID;dbFieldPosition=1;\"},{\"name\":\"contractId\",\"type\":[\"long\",\"null\"],\"meta\":\"dbFieldName=CONTRACT_ID;dbFieldPosition=2;\"}],\"meta\":\"dbFieldName=sy$prospect_update;pk=prospectId;\"}");
  public java.lang.Long txn;
  public java.lang.Long prospectId;
  public java.lang.Long contractId;
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return txn;
    case 1: return prospectId;
    case 2: return contractId;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: txn = (java.lang.Long)value$; break;
    case 1: prospectId = (java.lang.Long)value$; break;
    case 2: contractId = (java.lang.Long)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
}
