/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.linkedin.events.cappr;

@SuppressWarnings("all")
/** Auto-generated Avro schema for cappr.sy$prospect_history_1. Generated at Mar 14, 2012 08:18:56 PM PDT */
public class ProspectHistory_V1 extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = org.apache.avro.Schema.parse("{\"type\":\"record\",\"name\":\"ProspectHistory_V1\",\"namespace\":\"com.linkedin.events.cappr\",\"fields\":[{\"name\":\"txn\",\"type\":[\"long\",\"null\"],\"meta\":\"dbFieldName=TXN;dbFieldPosition=0;\"},{\"name\":\"uId\",\"type\":[\"long\",\"null\"],\"meta\":\"dbFieldName=U_ID;dbFieldPosition=1;\"},{\"name\":\"prospectId\",\"type\":[\"long\",\"null\"],\"meta\":\"dbFieldName=PROSPECT_ID;dbFieldPosition=2;\"},{\"name\":\"contractId\",\"type\":[\"long\",\"null\"],\"meta\":\"dbFieldName=CONTRACT_ID;dbFieldPosition=3;\"},{\"name\":\"projectId\",\"type\":[\"long\",\"null\"],\"meta\":\"dbFieldName=PROJECT_ID;dbFieldPosition=4;\"},{\"name\":\"dataType\",\"type\":[\"string\",\"null\"],\"meta\":\"dbFieldName=DATA_TYPE;dbFieldPosition=5;\"},{\"name\":\"snapshotDate\",\"type\":[\"long\",\"null\"],\"meta\":\"dbFieldName=SNAPSHOT_DATE;dbFieldPosition=6;\"},{\"name\":\"expireDate\",\"type\":[\"long\",\"null\"],\"meta\":\"dbFieldName=EXPIRE_DATE;dbFieldPosition=7;\"},{\"name\":\"dataValue\",\"type\":[\"string\",\"null\"],\"meta\":\"dbFieldName=DATA_VALUE;dbFieldPosition=8;\"}],\"meta\":\"dbFieldName=cappr.sy$prospect_history_1;pk=u_id;\"}");
  public java.lang.Long txn;
  public java.lang.Long uId;
  public java.lang.Long prospectId;
  public java.lang.Long contractId;
  public java.lang.Long projectId;
  public java.lang.CharSequence dataType;
  public java.lang.Long snapshotDate;
  public java.lang.Long expireDate;
  public java.lang.CharSequence dataValue;
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return txn;
    case 1: return uId;
    case 2: return prospectId;
    case 3: return contractId;
    case 4: return projectId;
    case 5: return dataType;
    case 6: return snapshotDate;
    case 7: return expireDate;
    case 8: return dataValue;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: txn = (java.lang.Long)value$; break;
    case 1: uId = (java.lang.Long)value$; break;
    case 2: prospectId = (java.lang.Long)value$; break;
    case 3: contractId = (java.lang.Long)value$; break;
    case 4: projectId = (java.lang.Long)value$; break;
    case 5: dataType = (java.lang.CharSequence)value$; break;
    case 6: snapshotDate = (java.lang.Long)value$; break;
    case 7: expireDate = (java.lang.Long)value$; break;
    case 8: dataValue = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
}
