# Basic Configuration Properties for cluster. Values given below are for App sandbox in CORP-ESV4 fabric
export DB_NAME=charlie-nsanghavi-ld.linkedin.biz
export ZK_HOST=esv4-be50.corp.linkedin.com
export ZK_PORT=2181
export ROUTER_HOST=esv4-be51.corp.linkedin.com
export ROUTER_PORT=12921
export STORAGE_CLUSTER_NAME=ESPRESSO_APP_DEV_SANDBOX

# These are number of maximum number relay instances on a given box
export MAX_NUM_INSTANCES=3

# Helix parameters
export HELIX_CONTROLLER_HOST=esv4-be50.corp.linkedin.com
export HELIX_CONTROLLER_PORT=12924
