/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.linkedin.events.following;
/*
 *
 * Copyright 2013 LinkedIn Corp. All rights reserved
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 *
*/


@SuppressWarnings("all")
/** Auto-generated Avro schema for following.SY$FOLLOW_SETTING. Generated at Nov 21, 2011 07:17:37 PM PST */
public class FollowSetting_V1 extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = org.apache.avro.Schema.parse("{\"type\":\"record\",\"name\":\"FollowSetting_V1\",\"namespace\":\"com.linkedin.events.following\",\"fields\":[{\"name\":\"txn\",\"type\":[\"int\",\"null\"],\"meta\":\"dbFieldName=TXN;dbFieldPosition=0;\"},{\"name\":\"id\",\"type\":[\"string\",\"null\"],\"meta\":\"dbFieldName=ID;dbFieldPosition=1;\"},{\"name\":\"entityType\",\"type\":[\"int\",\"null\"],\"meta\":\"dbFieldName=ENTITY_TYPE;dbFieldPosition=2;\"},{\"name\":\"entityId\",\"type\":[\"int\",\"null\"],\"meta\":\"dbFieldName=ENTITY_ID;dbFieldPosition=3;\"},{\"name\":\"key\",\"type\":[\"string\",\"null\"],\"meta\":\"dbFieldName=KEY;dbFieldPosition=4;\"},{\"name\":\"value\",\"type\":[\"string\",\"null\"],\"meta\":\"dbFieldName=VALUE;dbFieldPosition=5;\"},{\"name\":\"status\",\"type\":[\"string\",\"null\"],\"meta\":\"dbFieldName=STATUS;dbFieldPosition=6;\"}],\"meta\":\"dbFieldName=following.SY$FOLLOW_SETTING;\"}");
  public java.lang.Integer txn;
  public java.lang.CharSequence id;
  public java.lang.Integer entityType;
  public java.lang.Integer entityId;
  public java.lang.CharSequence key;
  public java.lang.CharSequence value;
  public java.lang.CharSequence status;
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return txn;
    case 1: return id;
    case 2: return entityType;
    case 3: return entityId;
    case 4: return key;
    case 5: return value;
    case 6: return status;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: txn = (java.lang.Integer)value$; break;
    case 1: id = (java.lang.CharSequence)value$; break;
    case 2: entityType = (java.lang.Integer)value$; break;
    case 3: entityId = (java.lang.Integer)value$; break;
    case 4: key = (java.lang.CharSequence)value$; break;
    case 5: value = (java.lang.CharSequence)value$; break;
    case 6: status = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
}
