/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.linkedin.events.mfeed;

@SuppressWarnings("all")
/** Auto-generated Avro schema for mfeed.sy$mfeed_stats_1. Generated at Sep 15, 2011 02:43:11 PM PDT */
public class MFeedStats_V1 extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = org.apache.avro.Schema.parse("{\"type\":\"record\",\"name\":\"MFeedStats_V1\",\"namespace\":\"com.linkedin.events.mfeed\",\"fields\":[{\"name\":\"txn\",\"type\":[\"int\",\"null\"],\"meta\":\"dbFieldName=TXN;dbFieldPosition=0;\"},{\"name\":\"key\",\"type\":[\"int\",\"null\"],\"meta\":\"dbFieldName=KEY;dbFieldPosition=1;\"},{\"name\":\"id\",\"type\":[\"int\",\"null\"],\"meta\":\"dbFieldName=ID;dbFieldPosition=2;\"},{\"name\":\"updateDate\",\"type\":[\"long\",\"null\"],\"meta\":\"dbFieldName=UPDATE_DATE;dbFieldPosition=3;\"},{\"name\":\"fullSummary\",\"type\":[\"string\",\"null\"],\"meta\":\"dbFieldName=FULL_SUMMARY;dbFieldPosition=4;\"}],\"meta\":\"dbFieldName=mfeed.sy$mfeed_stats_1;\"}");
  public java.lang.Integer txn;
  public java.lang.Integer key;
  public java.lang.Integer id;
  public java.lang.Long updateDate;
  public java.lang.CharSequence fullSummary;
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return txn;
    case 1: return key;
    case 2: return id;
    case 3: return updateDate;
    case 4: return fullSummary;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: txn = (java.lang.Integer)value$; break;
    case 1: key = (java.lang.Integer)value$; break;
    case 2: id = (java.lang.Integer)value$; break;
    case 3: updateDate = (java.lang.Long)value$; break;
    case 4: fullSummary = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
}
